### ISSUE TITLE
Rewrite `data.py` to load from HuggingFace datastets

### ISSUE THREAD

**Issue by Rohan138** [mukobi/Unadaptable-Foundation-Models#1]
We can tear out the current torchvision loaders; MNIST stuff has been moved to the `mnist` branch.

Note that for the [CAIS cluster](https://cluster.safe.ai/#sharing-files-and-folders-with-other-users), we should have our loaders check if the dataset is already in the `/datasets` folder.

We should prioritize the UFM and finetuning datasets and just use [`lm_eval`](https://github.com/EleutherAI/lm-evaluation-harness) for RPP:
- [WMDP](https://huggingface.co/datasets/cais/wmdp-corpora)
- [HarmfulQA](https://huggingface.co/datasets/declare-lab/HarmfulQA)
- ?

**Comment by mukobi** [comment]
See https://github.com/openfeedback/superhf/blob/main/src/superhf/data.py for an example of dataset loading for fine-tuning data--handle each dataset separately to get train and test.

Don't need to implement loading for the Relative Pretrain Perf datasets--Eleuther's lm-eval harness will take care of that.

**Comment by owen-yeung** [comment]
Dataset loader for the following identifiers/datasets implemented. Let me know if you need other datasets supported.

`dataset_identifier (str): The identifier for the dataset. Supported identifiers are:
            - "cyber" for the 'cais/wmdp-corpora' dataset with the 'cyber-forget-corpus' subset.
            - "harmfulqa" for the 'declare-lab/HarmfulQA' dataset.
            - "toxic" for the 'allenai/real-toxicity-prompts' dataset.
            - "pile" for the 'NeelNanda/pile-10k' dataset.`

**Comment by mukobi** [comment]
Note that we won't need this for running relative pretraining performance evals using the lm_eval harness, since it handles loading these datasets. But we might still use this for loading data fed into an unadaptability method.
