### ISSUE TITLE
Implement LM Eval Harness call in `pretrain_score.py`

### ISSUE THREAD

**Issue by m-walters** [mukobi/Unadaptable-Foundation-Models#10]
Potential duplicate of https://github.com/mukobi/Unadaptable-Foundation-Models/issues/7

From Apr 3rd [Meeting notes](https://docs.google.com/document/d/164bvxFsQ458-SvDVU6b2se5F9Btz3F8KLwQxl1qcj64/edit#heading=h.ij0xwv7j8ilo):

> Implement LM Eval Harness calling code in `pretrain_score.py` that gets waits for completion and gets the numbers in Python

**Comment by owen-yeung** [comment]
wandb script from
https://github.com/EleutherAI/lm-evaluation-harness/blob/main/examples/visualize-wandb.ipynb

Eval tasks from https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard

**Comment by mukobi** [comment]
For now, can just test a single eval like MMLU
