### ISSUE TITLE
FIM Loss calculation bug

### ISSUE THREAD

**Issue by m-walters** [mukobi/Unadaptable-Foundation-Models#24]
In `compute_fim_loss` (see [here](https://github.com/mukobi/Unadaptable-Foundation-Models/blob/73ef10649854fe000ee9222b5fe7294893960d22/src/ufm/unadapt.py#L43-L53)), the code will only work if `fim_reduce == "trace_max"`. @Rohan138  git blame at you, can you update this func as necessary to handle other `fim_reduce` values (if `None`, then what? throw exception?). Please add a docstring too.

**Comment by Rohan138** [comment]
Fixed in main
