### ISSUE TITLE
Make config and test main.py for Pythia-14M

### ISSUE THREAD

**Issue by mukobi** [mukobi/Unadaptable-Foundation-Models#27]
- Get Pythia-14M working
- Test our evaluation framework end-to-end
- Create new issues for things you notice we'll need to change (you don't need to fix those as part of this)

**Comment by mukobi** [comment]
@owen-yeung is this duped/fixed by #48?

**Comment by owen-yeung** [comment]
Modularize to parallelize and assign to others
