### ISSUE TITLE
run_fine_tune Training needs pad token/no batching

### ISSUE THREAD

**Issue by owen-yeung** [mukobi/Unadaptable-Foundation-Models#49]
When calling trainer.train() in fine_tuning.run_fine_tune:
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
 
Probably need to either add a padding token (and check if this alters any behavior) or switch to no batching/slow tokenizer or something

**Comment by mukobi** [comment]
Duped by #52
