### ISSUE TITLE
wandb.config object has no attribute 'finetune'

### ISSUE THREAD

**Issue by owen-yeung** [mukobi/Unadaptable-Foundation-Models#54]
<img width="718" alt="Screenshot 2024-05-19 at 11 56 39 AM" src="https://github.com/mukobi/Unadaptable-Foundation-Models/assets/77765487/f1e1790d-ddca-4f4f-9f06-c06bdb4bbd19">

Maybe the author meant the hydra config? Seems to me like the hydra config and wandb configs are two different things (see wandb docs)
https://docs.wandb.ai/guides/track/config

So maybe change the function to take the hydra config as input instead

**Comment by m-walters** [comment]
need to specify a config with the `finetune` struct/object to do finetuning
