### ISSUE TITLE
Restore old toy model scripts

### ISSUE THREAD

**Issue by m-walters** [mukobi/Unadaptable-Foundation-Models#9]
> Restore old toy model scripts for reproducing those figures - duplicate, don’t remove those files 

From Apr 3rd [Meeting notes](https://docs.google.com/document/d/164bvxFsQ458-SvDVU6b2se5F9Btz3F8KLwQxl1qcj64/edit)

**Comment by m-walters** [comment]
Potential duplicate of existing issue: https://github.com/mukobi/Unadaptable-Foundation-Models/issues/3

Delete this ticket if so

**Comment by Rohan138** [comment]
Done!
